### ISSUE TITLE
authorization doesn't seem to work

### ISSUE THREAD

**Issue by cremacs** [chiply/spot4e#5]
when I run `spot4e-authorize` I get sent to a web page that simply says, "Illegal redirect_uri".

**Comment by chiply** [comment]
Hi cremacs, thank you for taking the time to point out this issue. 

Unfortunately I can't seem to reproduce this error on my machine. 

I did some research as to what may be causing it, and I found [this](https://stackoverflow.com/questions/32956443/invalid-redirect-uri-on-spotify-auth/43453565), which suggests that the redirect uri must be white-listed, which has already been taken care of.

The redirect uri is https://spotify.com, and this is white-listed.  My only thought is that your browser might be redirecting you to spotify with a different TLD (top level domain), for example if you're in a different country.

Can I ask which country you're running the code from?

**Comment by cremacs** [comment]
Thanks for your response. I'm in the United States.

**Comment by jmoss20** [comment]
Hi chiply, I'm getting the same issue (also US based).  I've verified that "https://spotify.com" is being hexified properly in the authorization uri, but I'm not sure what else to check.

**Comment by chiply** [comment]
Hi all - reopening this issue as it seems I closed prematurely!  A fix is in the works, hold tight :-).  Out of curiosity, John, are you using emacs in the terminal of GUI?

**Comment by jmoss20** [comment]
I'm on GUI, but just checked the terminal and I'm getting the same error.  Thanks for taking a look!

**Comment by chiply** [comment]
Hey, I just merged a pull request that changed the way the auth url is encoded (this was from @christoofar, not sure why he isn't showing up as a contributor, or why this isn't tagging him properly).  It should work properly now, can you both check? 

See this commit https://github.com/chiply/spot4e/commit/1f9407b5ab1cb4857c092d279c6c36b9bdf64f2b

**Comment by jmoss20** [comment]
Still getting an illegal redirect_URI on my end.  Hard to tell just from the URI what the issue is -- I'll hunt around in Spotify docs later this week and see if I can find a problem.  Thanks for taking a look!
